name: XCS234_A3
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.4.0
  - tk>=8.6.8
  - matplotlib=3.3.4
  - numpy=1.20.1
  - scipy=1.6.2
  - gym=0.18.0
  - tensorboard=2.5.0
  - pytorch=1.8.1
  - pyyaml=5.4.1
  - glfw>=1.4.0
  - Cython>=0.27.2
  - cffi>=1.10
  - imageio>=2.1.2
  - fasteners~=0.15 
  - imagehash>=3.4 
  - Pillow>=4.0.0 
  - pycparser>=2.17.0
  - pytest>=3.0.5 
  - pip=21.1.3
  - pip:
    - mujoco-py==2.0.2.13
    - pytest-instafail==0.3.0 
    - gradescope-utils>=0.2.7


